GET http://localhost:3001/api/people

###
GET http://localhost:3001/api/people/2

###
GET http://localhost:3001
###

GET http://localhost:3001/api/notes/2

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "HI",
    "important": false
}