POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code peepee poopoo",
    "important": true
}

### break up requests with ###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}